; 分区表（来自 xiaomi-latte-flash_tools/gpt.ini，保持兼容）
; boot: 256MB ESP（FAT32），system: 占满剩余空间
[base]
partitions = boot pmOS

[partition.boot]
label = boot
len = 256
type = esp

[partition.pmOS]
label = system
len = -1
type = linux
guid = CC8CF58C-D70B-4BEB-ADB4-944040EAC3B0
